apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: otel-collector
  name: otel-collector-config
data:
  otel-collector-config.yaml: | 
    receivers:
      jaeger:
        protocols:
          grpc:

    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50

    exporters:
      otlp/data-prepper:
        endpoint: data-prepper-headless.default.svc:21890
        insecure: true
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          exporters: [logging, otlp/data-prepper]


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel/otel-collector-config.yaml
          image: otel/opentelemetry-collector:0.14.0
          name: otel-collector
          ports:
            - containerPort: 14250
          volumeMounts:
            - mountPath: /etc/otel/
              name: otel-collector-claim0
      restartPolicy: Always
      volumes:
        - name: otel-collector-claim0
          configMap:
            name: otel-collector-config          

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector
spec:
  clusterIP: None
  ports:
    - name: "14250"
      port: 14250
      targetPort: 14250
  selector:
    app: otel-collector

