version: "3.7"
services:
  otel-collector:
    container_name: otel-collector
    network_mode: host
    image: otel/opentelemetry-collector:0.14.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  jaeger-agent:
    container_name: jaeger-agent
    network_mode: host
    image: jaegertracing/jaeger-agent:latest
    command: [ "--reporter.grpc.host-port=localhost:14250" ]
  jaeger-hot-rod:
    container_name: jaeger-hotrod
    image: jaegertracing/example-hotrod:latest
    network_mode: host
    command: [ "all" ]
    environment:
      - JAEGER_AGENT_HOST=localhost
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger-agent

