entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      health_check_service: true
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - otel_trace_raw_prepper:
  sink:
    - elasticsearch: 
         hosts: [ "https://search-os-backup-eygwo6vtwhh653vuqpxntjjkjq.ap-south-1.es.amazonaws.com" ]
         aws_sigv4: false
         username: "admin"
         password: "xyz"
         trace_analytics_raw: true
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - service_map_stateful:
  sink:
    - elasticsearch: 
         hosts: [ "https://search-os-backup-eygwo6vtwhh653vuqpxntjjkjq.ap-south-1.es.amazonaws.com" ]
         aws_sigv4: false
         username: "admin"
         password: "xyz"
         trace_analytics_service_map: true         
